### PR TITLE
Small docstring fix for `sumo-dosplot`

### PR DESCRIPTION
**Pull request by kavanase**
Just noticed that the docstring for `zero-energy` in `sumo-dosplot` was incorrect (duplication of `zero-line` which has different behaviour), so just a small update

### CODE REVIEW

**Comment by kavanase** [comment]
Also added a docstring fix for `optplot.py`

**Review by ajjackson — APPROVED** [review]
Looks good to me.

If there was any resource to work on Sumo, we could use Literal type annotations to make this kind of thing much clearer in the code. (And enforce them with Pydantic/Beartype so they don't need explicit checks.)

Looking back at this code with a few more years of experience, it would also probably be a good idea to refactor the Vasp/Questaal paths into an object interface and eliminate a lot of the logic. Ah, well.

**Comment by ajjackson** [comment]
I know this is a small change but do feel free to mention these things in the CHANGELOG and claim your credit. We can always tidy them together into a "minor maintenance" item or something before release if they get unwieldy.

**Comment by ajjackson** [comment]
By the way, I see you did the work on `master` rather than create a feature branch; you might now have a bit of cleanup to do to get your local/forked `master` branch straight. Something like

```
git checkout master && git pull origin master  # Make sure local copy matches github fork
git remote add upstream git@github.com:smtg-bham/sumo.git  # Add main sumo repo as another remote
git fetch upstream master  # Get a copy of the master branch on this repo
git reset --hard upstream/master  # Move the "master" label on your local copy to be in sync with SMTG-Bham, and update local files to match. THIS WILL DELETE LOCAL CHANGES
git push --force-with-lease origin master  # Force "master" on your branch to match the same state. The "-with-lease" means this will error if your local copy of remote branch is out-of-date (i.e. somebody (i.e. me) pushed a commit you didn't pull yet).
```

**Pull request merged**
